// Pro Shoot — Brand Constants & Data

export const BRAND = {
  name: 'Pro Shoot',
  tagline: 'Capture Moments. Create Stories. Preserve Forever.',
  description: 'Premium photography and cinematic storytelling crafted for life\'s most meaningful moments.',
  phone: '+91 98765 43210',
  email: 'hello@proshoot.in',
  whatsapp: '919876543210',
  address: {
    line1: 'Pro Shoot Studios',
    line2: '42, MG Road, Indiranagar',
    city: 'Bangalore',
    state: 'Karnataka',
    pin: '560038',
    country: 'India',
    full: '42, MG Road, Indiranagar, Bangalore, Karnataka 560038',
    mapUrl: 'https://maps.google.com/?q=12.9716,77.5946',
  },
  social: {
    instagram: 'https://instagram.com/proshoot',
    facebook: 'https://facebook.com/proshoot',
    youtube: 'https://youtube.com/@proshoot',
    pinterest: 'https://pinterest.com/proshoot',
    linkedin: 'https://linkedin.com/company/proshoot',
  },
  hours: {
    weekdays: '10:00 AM – 7:00 PM',
    saturday: '10:00 AM – 5:00 PM',
    sunday: 'By Appointment Only',
  },
  founded: 2014,
  stats: {
    weddings: 500,
    years: 10,
    awards: 50,
    clients: 1000,
    projects: 2500,
    cities: 25,
  },
} as const;

export const SERVICES = [
  {
    slug: 'wedding-photography',
    title: 'Wedding Photography',
    shortTitle: 'Weddings',
    tagline: 'Where Love Meets Legacy',
    description: 'Every wedding is a universe of emotions, traditions, and fleeting moments. We don\'t just photograph weddings — we preserve the poetry of your most sacred day.',
    price: '₹75,000+',
    image: '/images/shoot-3.png',
    icon: 'Heart',
    featured: true,
  },
  {
    slug: 'pre-wedding-photography',
    title: 'Pre-Wedding Photography',
    shortTitle: 'Pre-Wedding',
    tagline: 'Stories Before The Story',
    description: 'Cinematic pre-wedding experiences that capture the chemistry, laughter, and anticipation before your big day. From destination shoots to intimate portraits.',
    price: '₹25,000+',
    image: '/images/shoot-2.png',
    icon: 'Sparkles',
    featured: true,
  },
  {
    slug: 'baby-photography',
    title: 'Baby Photography',
    shortTitle: 'Baby Shoots',
    tagline: 'Tiny Moments, Timeless Memories',
    description: 'Delicate, tender, and breathtaking. Our baby photography captures the pure magic of new life with artistic precision and infinite gentleness.',
    price: '₹15,000+',
    image: '/images/baby-shoot-1.png',
    icon: 'Baby',
    featured: true,
  },
  {
    slug: 'maternity-photography',
    title: 'Maternity Photography',
    shortTitle: 'Maternity',
    tagline: 'The Art of Becoming',
    description: 'Celebrate the extraordinary beauty of motherhood. Our maternity sessions blend artistic vision with intimate storytelling in luxury settings.',
    price: '₹20,000+',
    image: '/generated/maternity-1.png',
    icon: 'Flower2',
    featured: true,
  },
  {
    slug: 'corporate-photography',
    title: 'Corporate Photography',
    shortTitle: 'Corporate',
    tagline: 'Professional Presence, Powerful Impact',
    description: 'Executive portraits, team photography, event coverage, and brand documentation that elevates your professional image to industry-leading standards.',
    price: '₹30,000+',
    image: '/generated/corporate-1.png',
    icon: 'Building2',
    featured: false,
  },
  {
    slug: 'fashion-photography',
    title: 'Fashion Photography',
    shortTitle: 'Fashion',
    tagline: 'Where Vision Meets Vogue',
    description: 'Editorial fashion photography that commands attention. From lookbooks to campaign shoots, we create imagery that defines brands and inspires audiences.',
    price: '₹40,000+',
    image: '/generated/fashion-1.png',
    icon: 'Shirt',
    featured: true,
  },
  {
    slug: 'product-photography',
    title: 'Product Photography',
    shortTitle: 'Products',
    tagline: 'Every Product Has a Story',
    description: 'Luxury product photography for D2C brands, e-commerce, and advertising. We make products irresistible through masterful lighting and composition.',
    price: '₹20,000+',
    image: '/generated/product-1.png',
    icon: 'Package',
    featured: false,
  },
  {
    slug: 'real-estate-photography',
    title: 'Real Estate Photography',
    shortTitle: 'Real Estate',
    tagline: 'Spaces That Sell Themselves',
    description: 'Architectural and interior photography that transforms spaces into aspirations. Perfect for builders, architects, luxury villas, and hospitality brands.',
    price: '₹25,000+',
    image: '/generated/realestate-1.png',
    icon: 'Home',
    featured: false,
  },
  {
    slug: 'drone-photography',
    title: 'Drone Photography',
    shortTitle: 'Drone',
    tagline: 'Elevated Perspectives',
    description: 'Professional aerial photography and cinematography that reveals the grandeur invisible to the human eye. Licensed, insured, and cinematic.',
    price: '₹15,000+',
    image: '/sequences/drone_hover/frame_000120.png',
    icon: 'Plane',
    featured: true,
  },
  {
    slug: 'event-photography',
    title: 'Event Photography',
    shortTitle: 'Events',
    tagline: 'Every Event Deserves Remembrance',
    description: 'Corporate events, private celebrations, product launches, and cultural festivals captured with documentary precision and artistic flair.',
    price: '₹20,000+',
    image: '/generated/event-1.png',
    icon: 'Calendar',
    featured: false,
  },
  {
    slug: 'videography',
    title: 'Videography & Cinematography',
    shortTitle: 'Videography',
    tagline: 'Motion Pictures, Moving Hearts',
    description: 'Cinematic video production for weddings, events, brands, and commercial projects. From storytelling to highlight reels, every frame is cinema.',
    price: '₹50,000+',
    image: '/generated/video-1.png',
    icon: 'Video',
    featured: true,
  },
  {
    slug: 'cinematography',
    title: 'Cinematography',
    shortTitle: 'Cinema',
    tagline: 'Directing Light, Designing Emotion',
    description: 'Feature-grade cinematography for weddings, short films, and brand films. We bring Hollywood-caliber production values to every project.',
    price: '₹75,000+',
    image: '/generated/video-1.png',
    icon: 'Film',
    featured: false,
  },
  {
    slug: 'album-design',
    title: 'Album Design',
    shortTitle: 'Albums',
    tagline: 'Heirlooms Crafted By Hand',
    description: 'Luxury coffee-table albums designed with meticulous attention to layout, typography, and materials. Every album is a masterpiece you can hold.',
    price: '₹10,000+',
    image: '/generated/album-1.png',
    icon: 'BookOpen',
    featured: false,
  },
  {
    slug: 'photo-restoration',
    title: 'Photo Restoration',
    shortTitle: 'Restoration',
    tagline: 'Reviving Yesterday\'s Treasures',
    description: 'Expert digital restoration of damaged, faded, or aging photographs. We bring cherished memories back to life with painstaking precision.',
    price: '₹5,000+',
    image: '/generated/restoration-1.png',
    icon: 'RotateCcw',
    featured: false,
  },
] as const;

export const NAV_LINKS = [
  { label: 'Home', href: '/' },
  { label: 'About', href: '/about' },
  {
    label: 'Services',
    href: '/services',
    children: SERVICES.filter(s => s.featured).map(s => ({
      label: s.title,
      href: `/services/${s.slug}`,
    })),
  },
  { label: 'Portfolio', href: '/portfolio' },
  { label: 'Albums', href: '/albums' },
  { label: 'Rentals', href: '/rentals' },
  { label: 'Pricing', href: '/pricing' },
  { label: 'Blog', href: '/blog' },
  { label: 'Contact', href: '/contact' },
] as const;

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Priya & Arjun Sharma',
    event: 'Wedding Photography',
    location: 'Udaipur, Rajasthan',
    quote: 'Pro Shoot didn\'t just capture our wedding — they captured our souls. Every photograph feels like a painting. We relive our wedding every time we open our album.',
    rating: 5,
    image: '/images/shoot-3.png',
  },
  {
    id: 2,
    name: 'Ananya & Vikram Menon',
    event: 'Pre-Wedding Shoot',
    location: 'Kerala Backwaters',
    quote: 'The team understood our story before we even told it. The pre-wedding shoot felt like a Bollywood movie — effortless, romantic, and absolutely cinematic.',
    rating: 5,
    image: '/images/shoot-2.png',
  },
  {
    id: 3,
    name: 'Meera & Raj Patel',
    event: 'Baby Photography',
    location: 'Bangalore Studio',
    quote: 'Our daughter\'s newborn photos are the most precious possession we own. The patience, the artistry, the tenderness — Pro Shoot is simply unmatched.',
    rating: 5,
    image: '/images/baby-shoot-1.png',
  },
  {
    id: 4,
    name: 'Deepika Reddy',
    event: 'Fashion Editorial',
    location: 'Mumbai',
    quote: 'Working with Pro Shoot elevated my portfolio to international standards. Their understanding of light, mood, and storytelling is extraordinary.',
    rating: 5,
    image: '/images/shoot-3.png',
  },
  {
    id: 5,
    name: 'Suresh & Lakshmi Iyer',
    event: 'Destination Wedding',
    location: 'Goa',
    quote: 'From the first consultation to the final album delivery, every interaction felt premium. This is what luxury photography truly means.',
    rating: 5,
    image: '/images/shoot-2.png',
  },
  {
    id: 6,
    name: 'Karthik Nair',
    event: 'Corporate Headshots',
    location: 'Bangalore',
    quote: 'Our entire leadership team\'s portraits were transformed. Professional, modern, and perfectly aligned with our brand identity. Highly recommended.',
    rating: 5,
    image: '/images/shoot-3.png',
  },
];

export const FAQ_DATA = [
  {
    category: 'Booking',
    questions: [
      {
        q: 'How far in advance should I book?',
        a: 'For weddings and large events, we recommend booking 3-6 months in advance. Popular dates fill quickly, especially during wedding season (October-February). For other services, 2-4 weeks notice is typically sufficient.',
      },
      {
        q: 'What is the booking process?',
        a: 'Begin with an inquiry through our website, WhatsApp, or phone call. We\'ll schedule a consultation to understand your vision, discuss packages, and finalize details. A 30% advance secures your date.',
      },
      {
        q: 'Can I customize my package?',
        a: 'Absolutely. Every client is unique, and we believe your photography package should be too. All our packages can be tailored to your specific requirements, preferences, and budget.',
      },
    ],
  },
  {
    category: 'Pricing',
    questions: [
      {
        q: 'Why don\'t you display fixed prices?',
        a: 'Every project is unique in scope, duration, and creative requirements. Fixed pricing would either underserve premium clients or overcharge simpler projects. We provide transparent, customized quotes after understanding your needs.',
      },
      {
        q: 'What payment methods do you accept?',
        a: 'We accept bank transfers, UPI, credit/debit cards, and Razorpay for advance payments. A 30% advance is required to confirm your booking, with the balance due before the event.',
      },
    ],
  },
  {
    category: 'Services',
    questions: [
      {
        q: 'Do you travel for destination shoots?',
        a: 'Yes! We\'ve covered weddings and shoots across India and internationally — from Udaipur palaces to Santorini sunsets. Travel and accommodation for the team are quoted separately.',
      },
      {
        q: 'How long does it take to receive final photos?',
        a: 'Edited highlights are delivered within 7-10 business days. Complete galleries with full retouching take 4-6 weeks for weddings and 2-3 weeks for other services. Rush delivery is available.',
      },
      {
        q: 'Do you provide raw/unedited photos?',
        a: 'We deliver professionally edited images that represent our artistic vision and quality standards. Raw files are not included as they don\'t reflect our finished work, but can be discussed for premium packages.',
      },
    ],
  },
  {
    category: 'Technical',
    questions: [
      {
        q: 'What equipment do you use?',
        a: 'We use professional-grade Canon and Sony mirrorless systems, cinema-grade lenses, professional lighting setups, DJI drones, and RED/Blackmagic cinema cameras for videography.',
      },
      {
        q: 'Do you offer videography along with photography?',
        a: 'Yes, we offer combined photo and video packages. Having both teams from Pro Shoot ensures seamless coordination and a consistent visual style across all deliverables.',
      },
    ],
  },
];

export const BLOG_POSTS = [
  {
    slug: 'ultimate-guide-wedding-photography',
    title: 'The Ultimate Guide to Planning Your Wedding Photography',
    excerpt: 'Everything you need to know about choosing the right photographer, planning your timeline, and ensuring every moment is captured beautifully.',
    category: 'Wedding Tips',
    date: '2024-12-15',
    readTime: '8 min read',
    image: '/images/shoot-3.png',
    featured: true,
  },
  {
    slug: 'newborn-photography-tips',
    title: '10 Things to Know Before Your Baby\'s First Photoshoot',
    excerpt: 'From timing and feeding schedules to outfit choices and safety — expert advice for the perfect newborn photography session.',
    category: 'Baby Photography',
    date: '2024-11-28',
    readTime: '6 min read',
    image: '/images/baby-shoot-1.png',
    featured: false,
  },
  {
    slug: 'pre-wedding-destination-ideas',
    title: 'Top 15 Pre-Wedding Shoot Destinations in India',
    excerpt: 'From the palaces of Rajasthan to the beaches of Goa — discover the most stunning locations for your pre-wedding photography.',
    category: 'Pre-Wedding',
    date: '2024-11-10',
    readTime: '10 min read',
    image: '/images/shoot-2.png',
    featured: false,
  },
];
